### ISSUE TITLE
Why is exp_pd commented out?

### ISSUE THREAD

**Issue by rmjarvis** [herumi/fmath#8]
Could you comment on why the function `exp_pd` is commented out with a note saying "not fast"?  It looks like the same thing you do for `expd`, but doing two at once.  And it is pretty much exactly what you do in `expd_v` when `__AVX2__` isn't enabled.

Furthermore, I tried out the existing `exp_pd` code and it seems to be significantly faster than doing two `expd` calls.  And since I'm already writing code using `__m128d` variables, it is more convenient to not break out the two doubles, call `expd` twice, and then go back to `__m128d`.

Related to that, the code I'm working on is actually doing a non-integer power x^nu over an array of x values (as part of a longer calculation), which I'm implementing as `exp(nu * log(x))`.  The single-precision version looks like this:
```
__m128 xtothenu = fmath::exp_ps(_mm_mul_ps(nu, fmath::log_ps(x)));
```
So to make the corresponding double-precision code, I wrote my own `log_pd` that just calls out to the standard library
```
inline __m128d log_pd(__m128d x)
{
    union { __m128d m; double d[2]; } logx;
    logx.d[0] = std::log(*reinterpret_cast<double*>(&x));
    logx.d[1] = std::log(*(reinterpret_cast<double*>(&x)+1));
    return logx.m;
}
```
If you don't think it's possible to do a real "2 at once" version of log_pd that would be any faster than this, then maybe worth putting this into the fmath repo just to make life easier for people doing SSE2 operations and want to take a log of their `__m128d` values.

**Comment by herumi** [comment]
Thank you for your comment. I made `exp_pd` a few years ago and tested it on Haswell.
I forget details then I'll try again on recent CPU.

**Comment by herumi** [comment]
I'm sorry too late response.
I measured exp_pd on Haswell and Skylake, then the commented out version is faster on Skylake but the result is opposite on Haswell. Then I removed the comment and I added pow_ps, log_pd as you say.

**Comment by rmjarvis** [comment]
Awesome.  Thanks!
