### ISSUE TITLE
Compiling without xbyak

### ISSUE THREAD

**Issue by tmcclintock** [herumi/fmath#9]
I had trouble compiling the code because I do not have xbyak installed. Even though the README states that this is OK, headers for xbyak are imported on line 14 of bench.cpp and line 183 of fastexp.cpp. Both of these threw errors for me. I was able to compile fmath by not compiling bench.cpp at all, and then commenting out every line that involved xbyak and it's objects (e.g. every line that involved the clk object).

So either the README should be updated to reflect a non-optional dependence on xbyak, or the use of xbyak should be made optional. Thanks!

**Comment by herumi** [comment]
Thank you for your advice. I removed dependency to xbyak.

**Comment by tmcclintock** [comment]
Thanks! It works great.
